name: 'Tinto Brass Band, независимый уличный оркестр'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ab1ce0f0-ce6c-43a3-b269-cb2455f760aa.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7576d878-6150-4320-b5ad-f48804288817.png
layout_spectrum: 0.7318983984107871
typography_spectrum: 0.026093784246944106
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.8024512235633108
  lightness: 0.6989288197969556
  saturation: 0.8294138587857274
  rhythmicContrast: 0.9770728429104432
purpose:
  - type: contact
    label: Позвонить
    url: 'tel:+79646499392'
title: Tinto Brass Band
description: Одни из основателей движения брасс-бэндов в России
author:
  name: Gridsite made by eVr in Moscow with Love.
  url: 'http://youreka.ru'
  email: talalife@gmail.com
content_rating:
  adult: false
navigation:
  - name: Что мы делаем
    id: 68c7f6c1-c69a-4c71-aa0f-c8dc1a741ea2
    type: content
  - name: Костюмы и образы
    id: 57191697-dcd5-4365-aca5-2cd392fd43de
    type: content
  - name: Видео
    id: a405decc-de72-4d42-94b1-5a45aa97eb79
    type: content
  - name: Нам доверяют
    id: c9c7ae4d-77bc-4ee9-b8d2-31a31b8a459c
    type: content
  - name: История создания
    id: 26f8906a-d557-4bab-b253-f635af4a40ae
    type: content
  - name: Грамоты
    id: bf510236-e7c6-4cec-bf46-df5e1ab9b567
    type: content
  - name: Контакты
    id: 5c65dc1a-35ae-431d-b689-fa678bf9ab1e
    type: content
  - name: Инстаграм
    url: 'https://www.instagram.com/4appa/'
    type: external
  - name: ВК
    url: 'https://vk.com/tintobrassband'
    type: external
  - name: Фейсбук
    url: 'https://www.facebook.com/www.tintobrassband.ru/'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FCrjXTGAbWMY%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DCrjXTGAbWMY&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FCrjXTGAbWMY%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Дмитрий Сапарин
          url: 'https://www.youtube.com/user/saparind'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - weddind
        - свадьба
        - шоу
        - brass band
        - music
        - кавер
      description: Uploaded by Дмитрий Сапарин on 2017-04-17.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=CrjXTGAbWMY&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=CrjXTGAbWMY&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=CrjXTGAbWMY&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=CrjXTGAbWMY&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=CrjXTGAbWMY&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=CrjXTGAbWMY'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=CrjXTGAbWMY
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=CrjXTGAbWMY
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'http://www.youtube.com/watch?v=CrjXTGAbWMY'
      title: Tinto Brass Band - Свадебные Хулиганы ( Eng Teaser)
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
