name: 'Tinto Brass Band, независимый уличный оркестр'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ab1ce0f0-ce6c-43a3-b269-cb2455f760aa.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7576d878-6150-4320-b5ad-f48804288817.png
layout_spectrum: 0.7318983984107871
typography_spectrum: 0.026093784246944106
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.8024512235633108
  lightness: 0.6989288197969556
  saturation: 0.8294138587857274
  rhythmicContrast: 0.9770728429104432
purpose:
  - type: contact
    label: Позвонить
    url: 'tel:+79646499392'
title: Tinto Brass Band
description: Одни из основателей движения брасс-бэндов в России
author:
  name: Gridsite made by eVr in Moscow with Love.
  url: 'http://youreka.ru'
  email: talalife@gmail.com
content_rating:
  adult: false
navigation:
  - name: Что мы делаем
    id: 68c7f6c1-c69a-4c71-aa0f-c8dc1a741ea2
    type: content
  - name: Костюмы и образы
    id: 57191697-dcd5-4365-aca5-2cd392fd43de
    type: content
  - name: Видео
    id: a405decc-de72-4d42-94b1-5a45aa97eb79
    type: content
  - name: Нам доверяют
    id: c9c7ae4d-77bc-4ee9-b8d2-31a31b8a459c
    type: content
  - name: История создания
    id: 26f8906a-d557-4bab-b253-f635af4a40ae
    type: content
  - name: Грамоты
    id: bf510236-e7c6-4cec-bf46-df5e1ab9b567
    type: content
  - name: Контакты
    id: 5c65dc1a-35ae-431d-b689-fa678bf9ab1e
    type: content
  - name: Инстаграм
    url: 'https://www.instagram.com/4appa/'
    type: external
  - name: ВК
    url: 'https://vk.com/tintobrassband'
    type: external
  - name: Фейсбук
    url: 'https://www.facebook.com/www.tintobrassband.ru/'
    type: external
content: []
github: true
