name: Tinto Brass Band
analytics: {}
purpose:
  - type: contact
    label: Позвонить
    url: 'tel:+79646499392'
github: true
description: Одни из основателей движения брасс-бэндов в России
author:
  name: Gridsite made by eVr in Moscow with Love.
  url: 'http://youreka.ru'
  email: talalife@gmail.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="http://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FMoKy1BJacWw%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMoKy1BJacWw&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FMoKy1BJacWw%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Дмитрий Сапарин
          url: 'https://www.youtube.com/user/saparind'
          avatar: {}
      '@type': VideoObject
      keywords:
        - brass band
        - weddind
        - свадьба
        - шоу
        - кавер
        - cover
      title: Tinto Brass Band -Свадебные хулиганы ( Rus Teaser)
      starred: false
      isBasedOnUrl: 'http://www.youtube.com/watch?v=MoKy1BJacWw'
      publisher:
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        name: YouTube
        domain: www.youtube.com
        url: 'https://www.youtube.com/'
      description: Uploaded by Дмитрий Сапарин on 2017-04-17.
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - id: 68c7f6c1-c69a-4c71-aa0f-c8dc1a741ea2
    name: Что мы делаем
    type: content
  - id: 57191697-dcd5-4365-aca5-2cd392fd43de
    name: Костюмы и образы
    type: content
  - id: a405decc-de72-4d42-94b1-5a45aa97eb79
    name: Видео
    type: content
  - id: c9c7ae4d-77bc-4ee9-b8d2-31a31b8a459c
    name: Нам доверяют
    type: content
  - id: 26f8906a-d557-4bab-b253-f635af4a40ae
    name: История создания
    type: content
  - id: bf510236-e7c6-4cec-bf46-df5e1ab9b567
    name: Грамоты
    type: content
  - id: 5c65dc1a-35ae-431d-b689-fa678bf9ab1e
    name: Контакты
    type: content
  - type: external
    name: Инстаграм
    url: 'https://www.instagram.com/4appa/'
  - type: external
    name: ВК
    url: 'https://vk.com/tintobrassband'
  - type: external
    name: Фейсбук
    url: 'https://www.facebook.com/www.tintobrassband.ru/'
layout_spectrum: 0.7318983984107871
color:
  lightness: 0.6989288197969556
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  saturation: 0.8294138587857274
  brandStrength: 0.8024512235633108
  rhythmicContrast: 0.9770728429104432
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2096a707-8f1e-4943-ad12-bb693b33d164.jpg
content_rating:
  adult: false
typography_spectrum: 0.026093784246944106
opengraph: {}
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e5b7f651-8a93-4f7d-b9d2-ac6b5c36050c.jpg
title: Независимый уличный оркестр
